// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientsMicroService.Controllers.Data;


#nullable disable

namespace PatientsMicroService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250828083703_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatientsMicroService.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "1 Brookside St",
                            BirthDate = new DateOnly(1966, 12, 31),
                            FirstName = "Test",
                            Gender = "Female",
                            LastName = "TestNone",
                            PhoneNumber = "100-222-3333"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "2 High St",
                            BirthDate = new DateOnly(1945, 6, 24),
                            FirstName = "Test",
                            Gender = "Male",
                            LastName = "TestBorderLine",
                            PhoneNumber = "200-333-4444"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "3 Club Road",
                            BirthDate = new DateOnly(2004, 6, 18),
                            FirstName = "Test",
                            Gender = "Male",
                            LastName = "TestDanger",
                            PhoneNumber = "300-444-5555"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "4 Valley Dr",
                            BirthDate = new DateOnly(2002, 6, 28),
                            FirstName = "Test",
                            Gender = "Female",
                            LastName = "TestEarlyOnSet",
                            PhoneNumber = "400-555-6666"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
