// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotesMicroService.Data;

#nullable disable

namespace NotesMicroService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250828083631_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotesMicroService.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e1a2b97-ed2e-48b0-9c9e-d7e7fc99468e"),
                            Content = "Patient shows improvement in mobility exercises.",
                            PatientId = new Guid("db968684-8eab-4572-82ca-15439b5730fc")
                        },
                        new
                        {
                            Id = new Guid("746d18d2-3aa7-4adb-bc47-4f8fc2f0bcc0"),
                            Content = "Follow-up appointment scheduled for next week.",
                            PatientId = new Guid("db968684-8eab-4572-82ca-15439b5730fc")
                        },
                        new
                        {
                            Id = new Guid("9e83bf4b-5907-4289-87bb-ae5a33a825ec"),
                            Content = "Patient reports reduced pain levels.",
                            PatientId = new Guid("5abebeb4-40a8-4fa2-ad75-44ce81d133ea")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
